language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      env: R_CODECOV=true
      addons:
        apt:
          packages:
            - libv8-dev
    - os: osx
      osx_image: xcode7.2
      latex: false

r_github_packages:
  - richfitz/storr
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
